name: stohp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  # UI
  autocomplete_textfield: ^1.7.3
  # Util
  http: ^0.12.0+4
  qrscan: ^0.2.17
  qr_flutter: ^3.2.0
  # Hardware
  vibration: ^1.2.2
  # Bloc
  flutter_bloc: ^3.1.0
  equatable: ^1.0.2
  # Location
  geolocator: ^5.1.5
  google_maps_flutter: 0.5.21+15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  # adaptive_icon_background: "assets/icon/icon-background.png"
  # adaptive_icon_foreground: "assets/icon/icon-foreground.png"

flutter:
  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
  assets:
    - assets/icons/
    - assets/images/
